- type: replace
  path: /vm_extensions/-
  value:
    name: cfcr-master-network-properties
    cloud_properties:
      target_pool: ((cfcr_master_target_pool))
      tags:
      - ((cfcr_master_target_pool))
